
import Eye from '../assets/icons/Eye.svg'
import Logo from '../assets/images/logo.svg'
import Mail from '../assets/icons/mailicon.svg'
import World from '../assets/icons/worldicon.svg'
import CloseEye from '../assets/icons/closeeye.svg'
import Location from '../assets/icons/Location.svg'
import CellPhone from '../assets/icons/cellphone.svg'
import LogoWight from '../assets/images/logoWight.svg'
import ClanderIcon from '../assets/icons/calnder.svg'
import Slovakia from '../assets/images/Slovakiaflag.svg'
import BackgroundGradient from '../assets/images/LinearGradient.svg'
import BlackLogo from '../assets/images/blacklogo.svg'
import ButtonImage from '../assets/icons/BottomImage.svg'
import TravelInsurances from '../assets/images/Travelinsurance.svg'
import FlightBAg from '../assets/icons/FlightBag.svg'
import Flight from '../assets/icons/flightIcon.svg'
import FlagIcon from '../assets/icons/IconFlag.svg'
import Butonlogo from '../assets/icons/fontIcon.svg'
import BookMark from '../assets/icons/Bookmark.svg'
import Avtar from '../assets/icons/Avtar.svg'
import Wightlocation from '../assets/icons/wightlocation.svg'
import Background from '../assets/images/background.svg'
import WightLogo from '../assets/images/logoWight.svg'
import Italyflag from '../assets/images/flag.svg'
import NewsIcon from '../assets/icons/newicon.svg'
import BeachIcon from '../assets/icons/Beach.svg'
import Quintion from '../assets/icons/quitionmark.svg'
import BankIcon from '../assets/icons/bank.svg'
import Armania from '../assets/images/Armania.svg'
import HomeIcon from '../assets/icons/HomeIcon.svg'
import PLusIcon from '../assets/icons/Plus.svg'
import FAQ from '../assets/icons/FAQ.svg'
import SlovakiaBackground from '../assets/images/Slovakia_BAckgroundimage.svg'
import Backgroundsmall from '../assets/images/Backgroundsmall.svg'
import Application from '../assets/icons/Application.svg'
import Documents from '../assets/icons/Documentens.svg'
import Chatbot from '../assets/icons/chatbot.svg'
import Menu from '../assets/icons/Menu.svg'
import Home from '../assets/icons/Home.svg'
import WightApplication from '../assets/icons/WightAplication.svg'
import HomeGray from '../assets/icons/HomegRAY.svg'
import WightChat from '../assets/icons/WhightChatbot.svg'
import WightMenu from '../assets/icons/wightmenu.svg'
import WightDocuments from '../assets/icons/wightDouments.svg'
import Vistypeimage from '../assets/icons/vistypeimage.svg'
import Arrow from '../assets/icons/Arrow.svg'
import VisaTypeICone from '../assets/images/Visatypicone.svg'
import Check from '../assets/icons/check.svg'
import MinusButton from '../assets/icons/MinusButton.svg'
import PlusButton from '../assets/icons/PlusButton.svg'
import TravelInsurance from '../assets/icons/Travelinsurance.svg'
import Scooter from '../assets/icons/scooter.svg'
import PremiumLounge from '../assets/icons/Premium Lounge.svg'
import Message from '../assets/icons/Message.svg'
import CourierServices from '../assets/icons/CourierServices.svg'
import ProfileIcon from '../assets/icons/profileIcon.svg'
import CheckIcon from '../assets/icons/CheckIcon.svg'
import PrintIcon from '../assets/icons/ReprintIcon.svg'
import Cancel from '../assets/icons/Cancel.svg'
import LogOut from '../assets/icons/logouticon.svg'
import DeleteIcon from '../assets/icons/DeleteIcon.svg'
import Refresh from '../assets/icons/refresh.svg'
import Cancelicon from '../assets/icons/Cancelicon.svg'
import ProfileIconBox from '../assets/icons/profileIconbox.svg'
import ClanderIcon1 from '../assets/icons/ClanderIcon1.svg'
import ClanderIcon2 from '../assets/icons/ClanderIcon2.svg'
import Holidays from '../assets/icons/fontisto_holiday-village.svg'
import WeeklyIcon from '../assets/icons/WeeklyIcon.svg'

export {Logo,BlackLogo ,LogoWight,BackgroundGradient,Slovakia,Background,WightLogo,Italyflag,TravelInsurances,
    Application,Documents,Chatbot,Menu,Home,WightApplication,HomeGray,WightChat,WightMenu,WightDocuments,
    Backgroundsmall,VisaTypeICone
}
// icons
export {Eye,CloseEye ,Mail,CellPhone,World,Location,ClanderIcon,ButtonImage,DeleteIcon,Refresh,Cancelicon,
    FlagIcon,Flight,Butonlogo,BookMark,Avtar,NewsIcon,Quintion,BankIcon,HomeIcon,PLusIcon,FAQ,
Wightlocation,FlightBAg,BeachIcon,Armania,SlovakiaBackground,Vistypeimage,Arrow,Check,MinusButton,PlusButton,
TravelInsurance,Scooter,PremiumLounge,Message,CourierServices,ProfileIcon,CheckIcon,PrintIcon,Cancel,LogOut,ProfileIconBox,ClanderIcon1,ClanderIcon2
,Holidays,WeeklyIcon}